name: Valmora
version: "0.1"
main: org.nakii.valmora.Valmora
api-version: "1.21"
authors: [nakii]
description: A MMORPG engine for creating anything one can imagine.

commands:
  profile:
    usage: /profile help
  stat:
    usage: /stat help
  item:
    usage: /item help
  mob:
    usage: /mob help
  skill:
    usage: /skill help
    description: Master command for skills interactions.
  gui:
    usage: /gui help
    description: Gui debugging and opening commands.
