// Mirrors docs/modules/user/item.md — kept in sync with the shipped item schema.

export const RARITIES = [
  { id: "COMMON", color: "#ffffff" },
  { id: "UNCOMMON", color: "#55ff55" },
  { id: "RARE", color: "#5555ff" },
  { id: "EPIC", color: "#aa00aa" },
  { id: "LEGENDARY", color: "#ffaa00" },
  { id: "MYTHIC", color: "#ff55ff" },
  { id: "DIVINE", color: "#55ffff" },
] as const;

export const ITEM_TYPES = [
  "NONE",
  "SWORD",
  "AXE",
  "PICKAXE",
  "SHOVEL",
  "HOE",
  "TRIDENT",
  "BOW",
  "CROSSBOW",
  "FISHING_ROD",
  "SHEARS",
  "SHIELD",
  "ELYTRA",
  "HELMET",
  "CHESTPLATE",
  "LEGGINGS",
  "BOOTS",
  "HORSE_ARMOR",
  "PET",
  "ACCESSORY",
  "BACKPACK",
] as const;

export const STATS = [
  "health",
  "mana",
  "damage",
  "strength",
  "defense",
  "crit_chance",
  "crit_damage",
  "speed",
  "health_regen",
  "mana_regen",
  "luck",
  "mining_fortune",
  "mining_speed",
  "intelligence",
  "ferocity",
  "pet_luck",
  "sea_creature_chance",
  "fishing_speed",
  "trophy_fish_chance",
  "bonus_attack_speed",
  "ability_damage",
  "magic_find",
  "true_defense",
  "vitality",
  "farming_fortune",
  "foraging_fortune",
  "breaking_power",
  "mining_spread",
] as const;

export const TRIGGERS = [
  "RIGHT_CLICK",
  "LEFT_CLICK",
  "ON_HIT",
  "ON_KILL",
  "SNEAK",
  "ON_SHOOT",
  "PASSIVE",
  "EQUIP",
  "UNEQUIP",
  "ON_DAMAGE_TAKEN",
  "ON_TELEPORT",
] as const;

export const MECHANICS = [
  { id: "damage", params: "damage: 10\ndamage-type: MAGIC\ntarget: \"@target\"" },
  { id: "heal", params: "heal: 10\ntarget: \"@player\"" },
  { id: "apply_effect", params: "effect: slowness\nduration: 5.0\namplifier: 2\ntarget: \"@target\"" },
  { id: "modify_stat", params: "stat: strength\namount: 10\nduration: -1" },
  { id: "teleport", params: "distance: 8" },
  { id: "push_entities", params: "force: 1.5\ntarget: \"@enemies_in_radius{r=5}\"" },
  { id: "pull_entities", params: "strength: 1.5\ntarget: \"@enemies_in_radius{r=10}\"" },
  { id: "launch_projectile", params: "projectile: arrow\nvelocity: 2.0\ndamage: 10" },
  { id: "launch_player", params: "y-force: 1.0\nforward-force: 1.5" },
  { id: "ignite", params: "duration: 3\ntarget: \"@target\"" },
  { id: "give_coins", params: "amount: 50" },
  { id: "take_coins", params: "amount: 50" },
  { id: "aoe_mine", params: "radius: 1" },
] as const;

export const COMMON_MATERIALS = [
  "WOODEN_SWORD",
  "STONE_SWORD",
  "IRON_SWORD",
  "GOLDEN_SWORD",
  "DIAMOND_SWORD",
  "NETHERITE_SWORD",
  "BOW",
  "CROSSBOW",
  "TRIDENT",
  "STICK",
  "BLAZE_ROD",
  "DIAMOND_PICKAXE",
  "NETHERITE_PICKAXE",
  "LEATHER_HELMET",
  "IRON_HELMET",
  "DIAMOND_HELMET",
  "NETHERITE_HELMET",
  "DIAMOND_CHESTPLATE",
  "DIAMOND_LEGGINGS",
  "DIAMOND_BOOTS",
] as const;
