// The real module registration order from Valmora.java (see CLAUDE.md §5).
// Order matters at runtime — later modules may depend on earlier ones.
export const MODULE_CHAIN = [
  "script",
  "time",
  "stat",
  "player",
  "economy",
  "ui",
  "ability",
  "item",
  "mob",
  "skill",
  "combat",
  "gui",
  "recipe",
  "alchemy",
  "enchant",
  "zone",
  "resource",
  "fishing",
  "npc",
  "warp",
  "points",
  "notify",
  "quest",
  "collection",
  "hud",
  "calendar",
  "reforge",
  "pet",
  "progression",
] as const;

// A curated subset for the compact hero schematic — the modules a new admin
// meets first, in real chain order.
export const HERO_MODULES = [
  "script",
  "stat",
  "item",
  "mob",
  "combat",
  "gui",
  "recipe",
  "economy",
  "skill",
] as const;

export type ModuleId = (typeof MODULE_CHAIN)[number];

export const MODULE_LABELS: Record<string, string> = {
  script: "Script",
  time: "Time",
  stat: "Stat",
  player: "Player",
  economy: "Economy",
  ui: "UI",
  ability: "Ability",
  item: "Item",
  mob: "Mob",
  skill: "Skill",
  combat: "Combat",
  gui: "GUI",
  recipe: "Recipe",
  alchemy: "Alchemy",
  enchant: "Enchant",
  zone: "Zone",
  resource: "Resource",
  fishing: "Fishing",
  npc: "NPC",
  warp: "Warp",
  points: "Points",
  notify: "Notify",
  quest: "Quest",
  collection: "Collection",
  hud: "HUD",
  calendar: "Calendar",
  reforge: "Reforge",
  pet: "Pet",
  progression: "Progression",
};
